export const stationMap = new Map<string, string>([
  ['AIN', 'Ainola'],
  ['ALV', 'Alavus'],
  ['AVP', 'Aviapolis'],
  ['DRA', 'Dragsvik'],
  ['EPZ', 'Ähtärin Eläinpuisto-Zoo'],
  ['ENO', 'Eno'],
  ['EPO', 'Espoo'],
  ['HPJ', 'Haapajärvi'],
  ['HPK', 'Haapamäki'],
  ['HAA', 'Haarajoki'],
  ['HKS', 'Hankasalmi'],
  ['HNK', 'Hanko'],
  ['HKP', 'Hanko-Pohjoinen'],
  ['HVA', 'Harjavalta'],
  ['HNV', 'Heinävesi'],
  ['HKI', 'Helsinki'],
  ['HNN', 'Henna'],
  ['HR', 'Herrala'],
  ['HKH', 'Hiekkaharju'],
  ['HK', 'Hikiä'],
  ['HLS', 'Hillosensalmi (Repovesi)'],
  ['HP', 'Humppila'],
  ['HPL', 'Huopalahti'],
  ['HY', 'Hyvinkää'],
  ['HYT', 'Rautatiemuseo (Hyvinkää)'],
  ['HL', 'Hämeenlinna'],
  ['HM', 'Härmä'],
  ['HÖL', 'Höljäkkä'],
  ['ILM', 'Iisalmi'],
  ['ITA', 'Iittala'],
  ['ILA', 'Ilmala'],
  ['IMR', 'Imatra'],
  ['IKR', 'Inkeroinen'],
  ['IKO', 'Inkoo'],
  ['JNS', 'Joensuu'],
  ['JK', 'Jokela'],
  ['JRS', 'Jorvas'],
  ['JTS', 'Joutseno'],
  ['JJ', 'Juupajoki'],
  ['JY', 'Jyväskylä'],
  ['JÄS', 'Jämsä'],
  ['JR', 'Järvelä (Kärkölä)'],
  ['JP', 'Järvenpää'],
  ['KAJ', 'Kajaani'],
  ['KAN', 'Kannelmäki'],
  ['KNS', 'Kannus'],
  ['KR', 'Karjaa'],
  ['KRU', 'Karkku (Sastamala)'],
  ['KHA', 'Kauhava'],
  ['KLH', 'Kauklahti'],
  ['KNI', 'Kauniainen'],
  ['KA', 'Kausala (Iitti)'],
  ['KEM', 'Kemi'],
  ['KJÄ', 'Kemijärvi'],
  ['KML', 'Kempele'],
  ['KEA', 'Kera'],
  ['KE', 'Kerava'],
  ['KIÄ', 'Kerimäki'],
  ['KTI', 'Kesälahti'],
  ['KEU', 'Keuruu'],
  ['KIL', 'Kilo'],
  ['KKN', 'Kirkkonummi'],
  ['KIT', 'Kitee'],
  ['KRV', 'Kiuruvesi'],
  ['KTÖ', 'Kivistö'],
  ['KOH', 'Kohtavaara'],
  ['KVH', 'Koivuhovi'],
  ['KVY', 'Koivukylä'],
  ['KKI', 'Kokemäki'],
  ['KOK', 'Kokkola'],
  ['KLI', 'Kolari'],
  ['KLO', 'Kolho'],
  ['KON', 'Kontiomäki'],
  ['KRA', 'Koria'],
  ['KRS', 'Korso'],
  ['KTA', 'Kotka'],
  ['KTS', 'Kotkan satama'],
  ['KV', 'Kouvola'],
  ['KUO', 'Kuopio'],
  ['KUT', 'Kupittaa (Turku)'],
  ['KYN', 'Kylänlahti'],
  ['KY', 'Kymi'],
  ['KLN', 'Kyminlinna'],
  ['KÄP', 'Käpylä'],
  ['LH', 'Lahti'],
  ['LNA', 'Lapinlahti'],
  ['LR', 'Lappeenranta'],
  ['LAA', 'Lappila'],
  ['LPO', 'Lappohja'],
  ['LPA', 'Lapua'],
  ['LNÄ', 'Leinelä'],
  ['LPÄ', 'Lempäälä'],
  ['LEN', 'Helsinki Lentoasema'],
  ['LPV', 'Leppävaara'],
  ['LIS', 'Lieksa'],
  ['LM', 'Loimaa'],
  ['LOH', 'Louhela'],
  ['LUS', 'Lusto'],
  ['ML', 'Malmi'],
  ['MLO', 'Malminkartano'],
  ['MRL', 'Martinlaakso'],
  ['MAS', 'Masala'],
  ['MI', 'Mikkeli'],
  ['MIS', 'Misi'],
  ['MLA', 'Mommila'],
  ['MVA', 'Moskova (Leningradski)'],
  ['MH', 'Muhos'],
  ['MUL', 'Muurola'],
  ['MKI', 'Myllykoski'],
  ['MY', 'Myllymäki'],
  ['MYR', 'Myyrmäki'],
  ['MÄK', 'Mäkkylä'],
  ['MLÄ', 'Mäntsälä'],
  ['MR', 'Mäntyharju'],
  ['NSL', 'Nastola'],
  ['NVL', 'Nivala'],
  ['NOA', 'Nokia'],
  ['NRM', 'Nurmes'],
  ['OI', 'Oitti'],
  ['OV', 'Orivesi'],
  ['OVK', 'Orivesi keskusta'],
  ['OVB', 'Orivesi Matkahuolto'],
  ['OU', 'Oulainen'],
  ['OL', 'Oulu'],
  ['OLK', 'Oulunkylä'],
  ['PTI', 'Paimenportti'],
  ['PTO', 'Paltamo'],
  ['PAR', 'Parikkala'],
  ['PKO', 'Parkano'],
  ['PRL', 'Parola'],
  ['PSL', 'Pasila'],
  ['PAU', 'Pasila autojuna-asema'],
  ['PEL', 'Pello'],
  ['PVI', 'Petäjävesi'],
  ['PM', 'Pieksämäki'],
  ['PTR', 'Pietari (Finljandski)'],
  ['PTL', 'Pietari (Ladozhski)'],
  ['PH', 'Pihlajavesi'],
  ['PJM', 'Pitäjänmäki'],
  ['POH', 'Pohjois-Haaga'],
  ['PRI', 'Pori'],
  ['PLA', 'Puistola'],
  ['PMK', 'Pukinmäki'],
  ['PUN', 'Punkaharju'],
  ['PHÄ', 'Pyhäsalmi (Pyhäjärvi)'],
  ['PNÄ', 'Pietarsaari-Pedersöre (Pännäinen)'],
  ['PKY', 'Pääskylahti'],
  ['RKL', 'Rekola'],
  ['REE', 'Retretti'],
  ['RI', 'Riihimäki'],
  ['ROI', 'Rovaniemi'],
  ['RNN', 'Runni'],
  ['RKI', 'Ruukki'],
  ['RY', 'Ryttylä'],
  ['SLO', 'Salo'],
  ['BSP', 'Salo Piihovi'],
  ['STA', 'Santala'],
  ['SAU', 'Saunakallio'],
  ['SAV', 'Savio'],
  ['SL', 'Savonlinna'],
  ['SK', 'Seinäjoki'],
  ['SIJ', 'Siilinjärvi'],
  ['SPL', 'Simpele'],
  ['STI', 'Siuntio'],
  ['SGY', 'Skogby'],
  ['SKV', 'Sukeva'],
  ['SNJ', 'Suonenjoki'],
  ['TMS', 'Tammisaari'],
  ['TPE', 'Tampere'],
  ['TNA', 'Tapanila'],
  ['TSL', 'Tavastila'],
  ['TK', 'Tervajoki'],
  ['TRV', 'Tervola'],
  ['TSO', 'Tesoma (Tampere)'],
  ['TKL', 'Tikkurila (Vantaa)'],
  ['TL', 'Toijala (Akaa)'],
  ['TOL', 'Tolsa'],
  ['TRI', 'Tornio-Itäinen'],
  ['TRL', 'Tuomarila'],
  ['TU', 'Turenki'],
  ['TKU', 'Turku (Keskusta, Logomo)'],
  ['TUS', 'Turku satama'],
  ['TUU', 'Tuuri'],
  ['TVE', 'Tver'],
  ['UIM', 'Uimaharju'],
  ['UTJ', 'Utajärvi'],
  ['UKÄ', 'Uusikylä'],
  ['VAA', 'Vaala'],
  ['VS', 'Vaasa'],
  ['VNA', 'Vainikkala'],
  ['VMO', 'Valimo'],
  ['VMA', 'Vammala (Sastamala)'],
  ['VKS', 'Vantaankoski'],
  ['VAR', 'Varkaus'],
  ['VEH', 'Vehkala'],
  ['VTI', 'Vihanti (Raahe)'],
  ['VIH', 'Vihtari'],
  ['VIA', 'Viiala (Akaa)'],
  ['VNJ', 'Viinijärvi'],
  ['VYB', 'Viipuri'],
  ['VLH', 'Villähde'],
  ['VLP', 'Vilppula'],
  ['VSL', 'Vuonislahti'],
  ['YTR', 'Ylitornio'],
  ['YV', 'Ylivieska'],
  ['ÄHT', 'Ähtäri'],
]);

export const trainTypeMap = new Map<string, string>([
  ['IC', 'InterCity'],
  ['LOL', 'Lähijuna'],
  ['PYO', 'Yöjuna'],
  ['S', 'Pendolino'],
  ['SP', 'Pendolino Plus'],
  ['JLA', 'Ratatyöbussi'],
  ['BLV', 'Ratatyöbussi'],
  ['HDM', 'Kiskobussi'],
]);
